In [11]:
import pandas as pd

# Load dataset
df = pd.read_csv('../data/raw/imdb_movies.csv')

# Quick look
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10178 entries, 0 to 10177
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   names       10178 non-null  str
 1   date_x      10178 non-null  str
 2   score       10178 non-null  float64
 3   genre       10093 non-null  str
 4   overview    10178 non-null  str
 5   crew        10122 non-null  str
 6   orig_title  10178 non-null  str
 7   status      10178 non-null  str
 8   orig_lang   10178 non-null  str
 9   budget_x    10178 non-null  float64
 10  revenue     10178 non-null  float64
 11  country     10178 non-null  str
dtypes: float64(3), str(9)
memory usage: 954.3 KB

In [8]:
#inspecting What columns exist?
df.columns

Index(['names', 'date_x', 'score', 'genre', 'overview', 'crew', 'orig_title',
       'status', 'orig_lang', 'budget_x', 'revenue', 'country'],
      dtype='str')

In [10]:
#What looks wrong?
df.describe()

              score      budget_x       revenue
count  10178.000000  1.017800e+04  1.017800e+04
mean      63.497052  6.488238e+07  2.531401e+08
std       13.537012  5.707565e+07  2.777880e+08
min        0.000000  1.000000e+00  0.000000e+00
25%       59.000000  1.500000e+07  2.858898e+07
50%       65.000000  5.000000e+07  1.529349e+08
75%       71.000000  1.050000e+08  4.178021e+08
max      100.000000  4.600000e+08  2.923706e+09

In [13]:
# What is missing?
df.isnull().sum()

names          0
date_x         0
score          0
genre         85
overview       0
crew          56
orig_title     0
status         0
orig_lang      0
budget_x       0
revenue        0
country        0
dtype: int64

In [14]:
# Drop 'crew' column (not needed)
df = df.drop(columns=['crew'])

# Check missing again
df.isnull().sum()

names          0
date_x         0
score          0
genre         85
overview       0
orig_title     0
status         0
orig_lang      0
budget_x       0
revenue        0
country        0
dtype: int64

In [16]:
#Replace missing genre with "Unknown"
df['genre'] = df['genre'].fillna('Unknown')

In [19]:
df.isnull().sum()
df.head()

,names,date_x,score,genre,overview,orig_title,status,orig_lang,budget_x,revenue,country
0,Creed III,03/02/2023,73.0,"Drama, Action","After dominating the boxing world, Adonis Cree...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/2022,78.0,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
2,The Super Mario Bros. Movie,04/05/2023,76.0,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU
3,Mummies,01/05/2023,70.0,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU
4,Supercell,03/17/2023,61.0,Action,Good-hearted teenager William always lived in ...,Supercell,Released,English,77000000.0,3.409420e+08,US

In [20]:
df.to_csv('../data/cleaned/movies_cleaned.csv', index=False)